---
version: "3"
services:
  api-backend:
    stdin_open: true
    restart: always
    container_name: api-backend
    build:
      context: ./src
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - 10080:3000
    volumes:
      - ./src:/app/public
    depends_on:
      - api-database

  api-database:
    restart: always
    container_name: api-database
    image: mongo
    env_file:
      - .env
    expose:
      - 27017